
#Configuration file to run the GERDA ZAC Filter optimization
#DAQ (0=Struck, 1 = FlashCam)
DAQ: 1

#Energy window to scan
Energy:
  - 25000
  - 70000
#Energy:
#  - 12000
#  - 25000

#Standard analysis = 0, Pulser anlysis = 1
Pulser: 0

#nanoseconds
DAQBin: 16
#DAQBin: 40

#GERDA detector configuration file
#DAQconfig: "./GERDA.DAQconfig.run95.txt"
DAQconfig: "./DAQconfig-PGT-FlashCam.txt"

# This will be used as suffix to the calibration directory name
# DirSuffix: "FT12"

#microseconds
FilterLength: 57
#FilterLength: 155

#For filter parameters: start value; stop value; step

FlatTop:
  - 1.0
  - 1.0
  - 0.2

Sigma:
  - 2
  - 30
  - 2

Tau:
  - 160
  - 160
  - 50
